Django-1.6b1/cheesely_repo/cheesely/cheesely/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cheesely.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/',
        TemplateView.as_view(template_name='pages/about.html'),
        name='about'),
    url(r'^$',
        TemplateView.as_view(template_name='home.html'),
        name='home'),
    url(r'^cheeses/', include('cheeses.urls', namespace="cheeses")),
    url(r'^accounts/', include('registration.backends.simple.urls',),),
    url(r'^users/', include('users.urls', namespace="users")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django-1.6b1/cheesely_repo/cheesely/cheeses/urls.py
from django.conf.urls import patterns, url

from cheeses import views

urlpatterns = patterns('',
    # URL pattern for the CheeseListView
    url(
        regex=r'^$',
        view=views.CheeseListView.as_view(),
        name='list'
    ),
    # URL pattern for the CheeseDetailView
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.CheeseDetailView.as_view(),
        name='detail'
    ),
)

Django-1.6b1/cheesely_repo/cheesely/users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('', 

	# URL pattern for the UserDetailView
	url(
	    regex=r'^(?P<username>[\w\-_]+)/$',
	    view=views.UserDetailView.as_view(),
	    name='detail'
	),
	# URL pattern for the UserUpdateView
	url(
	    regex=r'^~edit/$',
	    view=views.UserUpdateView.as_view(),
	    name='update'
	),
)

Django-1.6b1/cheesely_repo/cheesely/cheeses/models.py
from django.db import models

# Create your models here.

class Cheese(models.Model):
    FIRMNESS_UNSPECIFIED = 1
    FIRMNESS_SOFT = 2
    FIRMNESS_HARD = 3

    FIRMNESS_CHOICES = (
        (FIRMNESS_UNSPECIFIED, 'unspecified'),
        (FIRMNESS_SOFT, 'soft'),
        (FIRMNESS_HARD, 'hard'),
    )

    name = models.CharField("Name of Cheese", max_length=255)
    description = models.TextField("Description", blank=True,
                null=True)
    firmness = models.IntegerField("Firmness", max_length=20,
                choices=FIRMNESS_CHOICES, null=True, blank=True)
    country_of_origin = models.CharField("Country of Origin",
                            max_length=255, blank=True, null=True)
    region_of_origin = models.CharField("Region of Origin",
                            max_length=255, blank=True, null=True)
    photo = models.ImageField("Photo", upload_to="cheeses",
                                        blank=True, null=True, default="") 
    photo_attribution = models.URLField("Photo Attribution",
		    max_length=255, blank=True, null=True, default="")

    def __unicode__(self): 
        # To display the actual name 
        # and not "Cheese object"
        return self.name

Django-1.6b1/cheesely_repo/cheesely/users/models.py
# Import the AbstractUser model
from django.contrib.auth.models import AbstractUser
# Import the basic Django ORM models library
from django.db import models

# Subclass AbstractUser
class User(AbstractUser):
	tagline = models.CharField("TagLine", 
			max_length=176, blank=True)

Django-1.6b1/cheesely_repo/cheesely/users/forms.py
from django import forms

from .models import User

class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
	model = User

	# Constrain the UserForm to just these fields.
	fields = ("tagline", "first_name", "last_name", "email")

Django-1.6b1/cheesely_repo/cheesely/cheeses/views.py
#from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Cheese

# Create your views here.
class CheeseListView(ListView):
	model = Cheese
	template_name = 'cheeses/cheese_list.html'

class CheeseDetailView(DetailView):
    model = Cheese
    template_name = 'cheeses/cheese_detail.html'

Django-1.6b1/cheesely_repo/cheesely/users/views.py
from django.shortcuts import render
# Import the detail view
from django.views.generic import DetailView
# Import the customized User model
from .models import User
# Only authenticated users can access views using this.
from braces.views import LoginRequiredMixin
# Import the form from users/forms.py
from .forms import UserForm
from django.core.urlresolvers import reverse
from django.views.generic import UpdateView
# Only authenticated users can access views
from braces.views import LoginRequiredMixin

class UserDetailView(DetailView):
	model = User
	# index lookups by username
	slug_field = "username"
	slug_url_kwarg = "username"

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    # Use the custom form to constrain displayed fields
    form_class = UserForm
    # send the user back to their own page after a successful update
    def get_success_url(self):
	    return reverse("users:detail",
			    kwargs={"username": self.request.user.username})
    def get_object(self):
	    # only get the User record for the user making the request
	    return User.objects.get(username=self.request.user.username)

Django-1.6b1/cheesely_repo/cheesely/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock title %} - Cheesely</title>
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}"
                    rel="stylesheet" media="screen" />
    <link href="{% static 'css/cheesely.css' %}"
                    rel="stylesheet" media="screen" />
  </head>
  <body>
    <div class="container">

      <div class="navbar">
        <div class="navbar-inner">
          <a class="brand" href="{% url 'home' %}">Cheesely</a>
          <ul class="nav">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
	    <li><a href="{% url 'cheeses:list' %}">Cheeses</a></li>
	    <li><a href="{% url 'registration_register' %}">
		    Sign Up!</a><li>
          </ul>
        </div>
      </div>

        {% block content %}
        {% endblock content %}
	<div class="cheese_pic">
		<img src="/static/img/fromage.jpg" alt="cheeses">
		<!--<p> credit - <a href="http://passeportsante.net">passeportsante.net</a> </p>-->
		<p>Eléonore@2013</p>
	</div>
	
    </div>

    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

Django-1.6b1/cheesely_repo/cheesely/templates/cheeses/cheese_detail.html
{% extends "base.html" %}

{% block title %}Cheeses: {{ cheese.name }}{% endblock %}

{% block content %}

<div class="row">
	<div class=navigation>
		<div class=back>
			{% if cheese.id > 1 %}
			<a href="{% url 'cheeses:detail' cheese.pk %}">
				    Previous
			    </a>
			{% endif %}
		</div>
		<a href="{% url 'cheeses:list' %}">Back to Cheese list
		</a>
		<div class=next>
			<!--{% if cheese.id  %}
				Next
				{% endif %}-->
		</div>
	</div>
    <div class="span6">
        <h2>{{ cheese.name }}</h2>
        {% if cheese.description %}
	<div class="description"> 
		<p>{{ cheese.description }}</p>
	</div>
        {% endif %}

        {% if cheese.firmness %}
            <p>Firmness: {{ cheese.get_firmness_display }}</p>
        {% endif %}
        
        {% if cheese.country_of_origin or cheese.region_of_origin %}
		    <h4>Origin</h4>

		    {% if cheese.country_of_origin %}
		        <p>Country: {{ cheese.country_of_origin }}</p>
		    {% endif %}

		    {% if cheese.region_of_origin %}
		        <p>Region: {{ cheese.region_of_origin }}</p>
		    {% endif %}

		{% endif %}
    </div>
    <div class="span">
	{% if cheese.photo %}
	    <img class="img-polaroid" src="{{ cheese.photo.url }}" />
	{% endif %} <br>
	{% if cheese.photo_attribution %}
	    <small><a href="{{ cheese.photo_attribution }}">{{ cheese.photo_attribution }}</a></small>
	{% endif %}
    </div>
</div>
{% endblock content %}

Django-1.6b1/cheesely_repo/cheesely/templates/cheeses/cheese_list.html
{% extends "base.html" %}

{% block title %}Cheese List{% endblock %}

{% block content %}
<div class="row">
    <div class="span12">
        <h2>Cheese List</h2>
        {% for cheese in cheese_list %}
        <h3>
            <a href="{% url 'cheeses:detail' cheese.pk %}">
                {{ cheese.name }}
            </a>
        </h3>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Django-1.6b1/cheesely_repo/cheesely/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

<div class="row">
    <div class="span12">

        <h2>Welcome to Cheesely</h2>

        <h5>Cheesely is a one-stop place for cheese lovers and cheese
	producers to share cheese.</h5>

	<div class="sub_row">
		<h4>View <a href="{% url 'cheeses:list' %}">Cheeses</a> or
		<a href="{%  url 'registration_register' %}">sign up</a> to add more!</h4>
	</div>
    </div>
</div>
{% endblock content %}

Django-1.6b1/cheesely_repo/cheesely/templates/pages/about.html
{% extends "base.html" %}

{% block title %}About{% endblock title %}

{% block content %}

<div class="row">
    <div class="span12">

        <h2>About Cheesely</h2>

        <p>Cheesely was founded in 2013 by three people who loved
        cheese a little too much for their own sanity.</p>

    </div>
</div>

{% endblock content %}